### ISSUE TITLE
Bug Report: Connecting to Gateway

### ISSUE THREAD

**Issue by vagabondlol** [dmod-gg/dmod#21]
Bug: The "Connecting to Gateway" message is on the site 24/7 no matter whether or not you are actually connecting.

How to reproduce: Just hop on the site.

Screenshot/Recording:
![Screen Shot 2021-08-11 at 5 27 44 PM](https://user-images.githubusercontent.com/48355895/129057997-6654bf72-dbcb-42fa-a99b-188383cc662e.png)

**Comment by acdvs** [comment]
Happening to me as well.

![image](https://user-images.githubusercontent.com/8650006/129087603-ea95a37b-3a53-462e-b529-a5659559faa1.png)

**Browser:** Brave v1.27.111 (Chromium: 92.0.4515.131)

**Comment by MattA-Official** [comment]
This has been hidden in the frontend for now, but there may still be a backend issue.
