### ISSUE TITLE
Bug Report: Profile options don't go away 

### ISSUE THREAD

**Issue by vagabondlol** [dmod-gg/dmod#22]
Bug: When you click on your profile icon to bring up options, then click on an option, when the page loads the dropdown doesn't go back up. You need to click somewhere for it to go away.

How to reproduce: Sign in > Click your profile icon > click on settings or profile > load the page > it's still dropped-down. 

Screenshot/Recording:

https://user-images.githubusercontent.com/48355895/129058521-5ecdaafc-2093-4a9f-a270-c3ab0065079c.mov

**Comment by Wilbert-mad** [comment]
This has been fixed 👍
