### ISSUE TITLE
Bug Report: Old embed 

### ISSUE THREAD

**Issue by vagabondlol** [dmod-gg/dmod#23]
Bug: The link beta.dmod.gg uses the old embed without the correct image or text. Pls replace it with the one we use for dmod.gg

How to reproduce: just type in https://beta.dmod.gg in discord

Screenshot/Recording:
![Screen Shot 2021-08-11 at 5 43 08 PM](https://user-images.githubusercontent.com/48355895/129060592-77d34848-a03d-4f24-9733-cc33a4070bab.png)

**Comment by MattA-Official** [comment]
It should be fixed in commit ccf08248aee19ef8378f2099d95582860316c15c

**Comment by vagabondlol** [comment]
> It should be fixed in commit [ccf0824](https://github.com/dmod-gg/dmod/commit/ccf08248aee19ef8378f2099d95582860316c15c)

didn't work...
img: 
![Screen Shot 2021-08-11 at 9 00 54 PM](https://user-images.githubusercontent.com/48355895/129087548-503ae6eb-6928-4a9f-81aa-3fe7eeaa7b5c.png)

**Comment by GamerCreator1** [comment]
Fixed as shown in the image!
![image](https://user-images.githubusercontent.com/58714825/129220792-13b51dfc-cc80-47d0-bcc2-27b7d3106116.png)
