### ISSUE TITLE
Bug Report: Footer is really big & hovering makes a weird animation

### ISSUE THREAD

**Issue by vagabondlol** [dmod-gg/dmod#25]
Bug: The site's footer is super large, please check https://giggl.app 's footer for size reference. Also, the animation is super freaky, maybe make it smoother. Again, giggl is great for referencing a nice style 

How to reproduce: Just load up the website and check out the footer

Screenshot/Recording:

https://user-images.githubusercontent.com/48355895/129060865-e4259fda-5d1d-47ad-a9ab-72fee3f234c3.mov

**Comment by MattA-Official** [comment]
fixed in 27da46d8cb5b78119f26a43fd649dd4e892c1cee
