### ISSUE TITLE
Bug Report: 404 page is too large

### ISSUE THREAD

**Issue by vagabondlol** [dmod-gg/dmod#26]
Bug: The 404 page is too big, the correct size is on the pre-launch site's 404 page.

How to reproduce: Type in an invalid beta domain (https://beta.dmodgg/lol) for example.

Screenshot/Recording:

https://user-images.githubusercontent.com/48355895/129061394-980f0b13-90f6-4421-b89e-05bbffb47e51.mov

**Comment by MattA-Official** [comment]
fixed in 27da46d8cb5b78119f26a43fd649dd4e892c1cee
