### ISSUE TITLE
Bug Report: Enter with search doesn't work

### ISSUE THREAD

**Issue by vagabondlol** [dmod-gg/dmod#29]
Bug: Only the search button works when clicked, but it should also work when I press enter on my keyboard

How to reproduce: Search something and press enter; it won't work

Screenshot/Recording:

https://user-images.githubusercontent.com/48355895/129083239-8685e9a8-62d4-4b44-8669-171ee7301ef6.mov

**Comment by Wilbert-mad** [comment]
This has been fixed 👍
