### ISSUE TITLE
Bug Report: No staff badges

### ISSUE THREAD

**Issue by vagabondlol** [dmod-gg/dmod#32]
this doesn't need explaining B)

**Comment by MattA-Official** [comment]
I think I added some of them, but I am yet to properly work out the bit flags.

**Comment by vagabondlol** [comment]
> I think I added some of them, but I am yet to properly work out the bit flags.

flags? as in like the popup text upon hover, or

**Comment by MattA-Official** [comment]
> > I think I added some of them, but I am yet to properly work out the bit flags.
> 
> flags? as in like the popup text upon hover, or

bit flags as in programming, not any sort of popup text.
