### ISSUE TITLE
Changes to the open source code

### ISSUE THREAD

**Issue by Connor200024** [dmod-gg/dmod#4]
Hi,

I have a few things i wish to point out as i see this is open source now....

Frist off you are exposing Window's Database. (This is in the .env)

Another thing, you are exposing your token.... (Ish stupid ngl, come on devs should know this stuff)

Please fix this, i am only saying this because some one someone is gonna attempt something stupid... Welcome to the internet! 😊

Thanks,

Connor200024

**Comment by MaximKing1** [comment]
https://github.com/dmod-gg/dmod/pull/3
Fixed the changes here

**Comment by MattA-Official** [comment]
duplicate of #5 (exposure of environmental files)

**Comment by MattA-Official** [comment]
duplicate of #5
