### ISSUE TITLE
Bug Report: Issue with the enter button on searching

### ISSUE THREAD

**Issue by vagabondlol** [dmod-gg/dmod#47]
Bug: If you search something up in the search bar and click enter one time, then if you type something in again without clicking outside of the search bar and press enter, it won't work. You need to manually click search. 

Reproduce: Search Bar > Type something > press enter > type something else > Press enter > nothing happens

Img/Video:
no point in having a pic or vid

**Comment by Wilbert-mad** [comment]
This was fixed on: 6b0d32f48229061814c8e44cc33964d5fc43123d though it hasn't been added to the main site.
