### ISSUE TITLE
Conventional fixes 

### ISSUE THREAD

**Issue by EncryptedDev** [dmod-gg/dmod#5]
Well, as I explained during my time within the project, there are many bad practices straight off the bat there. I've proceeded to list a few, however, the great extent of the issues are still unknown :/

- Exposure of environmental files, such as `.env`
- In `.scss` files, fixed positional elements are used (`px`). Instead, you should use relative values (`em`, `clamp()`). Better practice on smaller viewports and scaling in general. Using fixed values is frowned upon by many stylist developers as Apple scale fonts etc for the display port size. 
- Consistency through using TypeScript and JavaScript 
- Two applications shouldn't be on one repository for obvious reasons
- If you're using Next.js, why aren't you using Next.js API routes?

Over time, if I locate more issues, I'll add them to this thread. I'll also work on this a little bit as and when I get the time. 
If you have any issues, comment them below and I'll respond when I get the time to.

**Comment by MattA-Official** [comment]
For all the issues you have listed, they should get fixed in the rewrite (#1) This thread will remain open for any further issues. 

Anyone who is contributing should add a comment detailing each breach of convention.
