### ISSUE TITLE
Bug Report: Arrows in footer are broken

### ISSUE THREAD

**Issue by vagabondlol** [dmod-gg/dmod#53]
Bug: The arrows on the working links in the site footer are under the actual links

Reproduce: load up the site and look at the footer

Img/Video:
![Screen Shot 2021-08-17 at 2 25 25 PM](https://user-images.githubusercontent.com/48355895/129725226-097e810e-0e41-4281-b1c0-c0182c8abd94.png)

**Comment by MattA-Official** [comment]
Blame it on tailwind
