### ISSUE TITLE
Bug Report: profile dropdown is funky

### ISSUE THREAD

**Issue by vagabondlol** [dmod-gg/dmod#60]
Bug: When you click ur profile icon the dropdown goes to the right rather than the left

Reproduce: click on profile dropdown, look at it

Img: 
![Screen Shot 2021-08-17 at 3 58 28 PM](https://user-images.githubusercontent.com/48355895/129739345-cbc64ac9-e174-47e1-9309-8f708c4f3730.png)

**Comment by MattA-Official** [comment]
fixed in c07a2144f96c10352ebd6e7b84ffec052c6b71ed
